tellor-io/layer

README.md
Added the step-by-step commands that worked for me when running the chain locally.
=> Steps added for Starting the Chain Locally

x/registry/keeper/query_test.go
wrote the easiest test I could to get used to it
=> query_test

start_scripts/start_one_node_aws.sh
trying to merge in a working aws script to see if that works with my new instance
=> fixed merge issue on aws script

local_devnet/layer-app/genesis.json, local_devnet/scripts/start_node_and_create_validator.sh
make it so that voting period is automatically shorter in local_devnet as well as the SpotPrice buffer window being 2s
=> updated genesis file and script in local_devnet

tests/e2e/basic_dispute_test.go, tests/e2e/basic_reporting_test.go, tests/integration/oracle_keeper_test.go, tests/integration/tipping_test.go, x/oracle/keeper/keeper.go, x/oracle/keeper/submit_value_test.go, x/registry/types/dataspec.go
changed submit window offset from 3s to 6s. Changed SpotPrice ReportBufferWindow from 3s to 6s
=> Increase Report Window Time

local_devnet/upgrade_test.sh
Removes local paths from one script in main
=> Removes local paths

x/dispute/keeper/execute.go
Addressing this: https://github.com/tellor-io/layer/issues/503
=> added the updating of the JailedUntil field to another case in execute.go

daemons/reporter/client/broadcast_message.go, daemons/reporter/client/tx_handler.go
No state changes. Just changed two hardcoded numbers to be different.
=> increased timeouts for reporter daemon to account for longer block times

daemons/reporter/client/broadcast_message.go, daemons/reporter/client/client.go
Fix daemon bug which prevented previously reported bridge deposits from being reported again.
N/A
=> fix: allow tipped deposit reporting

layer_scripts/configure_layer_linux.sh, layer_scripts/configure_layer_mac.sh
These config scripts are referred to in the layer-docs (gitbook). They have been updated with a new RPC and peers list for layertest-4.
=> config scripts updated for palmito

adr/adr2002 - ordering properties for user data and validator set updates.md, adr/adr2008 - token bridge withdraws and state pruning
Added ADR regarding state expiry and token withdraws. Also updated existed ADR adding lastConsensusTimestamp
=> bridge adr updates

app/upgrades.go, app/upgrades/v4.0.3/constants.go, app/upgrades/v4.0.3/upgrade.go, daemons/cmd/main.go, daemons/go.mod, daemons/go.sum
updated the upgrade folder in the app folder to use the upgrade handler for v4.0.3
Fixes #
- [ x ] Chain Changes (please describe): implemented upgrade handler to be used in the next upgrade
- [ x ] Daemon Changes: added line to load environment variables from files to accommodate for users who set variables in files
Need to get merged into the release branch so I can do a full upgrade run through
- [ x ] Code follows project style guidelines
- [ x ] I have added appropriate comments to my code
- [ x ] I have updated the documentation accordingly
- [ x ] I have added tests that prove my fix or feature works
- [ x ] go test ./... is passing locally
- [ x ] make e2e is passing locally
=> UPGRADE: implemented v4.0.3 upgrade handler

evm/contracts/bridge/TellorDataBridge.sol, evm/contracts/bridge/mock/BridgeCaller.sol, evm/contracts/interfaces/ITellorDataBridge.sol, evm/contracts/testing/SimpleLayerUser.sol, evm/contracts/testing/TellorDataBridgeTestnet.sol, evm/contracts/testing/UsingTellor.sol, evm/contracts/token-bridge/TokenBridge.sol, evm/hardhat.config.js, evm/scripts/DeployBridgewithTokenBridge.js, evm/scripts/DeploySimpleLayerUser.js, evm/scripts/DeployTellorDataBridge.js, evm/test/BlobstreamOFunctionTestsHH.js, evm/test/TokenBridgeFunctionTestsHH.js, evm/test/TokenBridgeTransition-E2EForking.js, evm/test/TokenBridgeTransition-FunctionTests.js, evm/test/helpers/evmHelpers.js, evm/test/helpers/helpers.js
Renamed BlobstreamO contract to TellorDataBridge
Fixes #
=> chore: rename blobstream contract

.github/workflows/release.yml, .github/workflows/statechange.yml
=> Edit release workflow

pagination-guide.md
Information about and examples using pagination
Fixes #
=> docs: pagination

daemons/pricefeed/client/client.go, daemons/telemetry.go, scripts/vote-ext-monitor/vote_ext_participation_rate_monitor.go, scripts/weekly-reports-generator/README.md, scripts/weekly-reports-generator/weekly-reports-generator.go
This script will generate weekly discord alerts covering vote extension participation rates (by power not number of validators) and the frequency of bridge validator set updates.
Fixes #
- [ x ] New feature
Ran the script locally using the -run-once flag to analyze some local csv data files. 
- [ x ] Code follows project style guidelines
- [ x ] I have added appropriate comments to my code
- [ x ] I have updated the documentation accordingly
- [ x ] I have added tests that prove my fix or feature works
- [ x ] go test ./... is passing locally
- [ x ] make e2e is passing locally
=> Feat: Weekly Reports Script

scripts/setup/initial_config/configure_mainnet_linux.sh, scripts/setup/initial_config/configure_mainnet_mac.sh, scripts/setup/initial_config/configure_palmito_linux.sh, scripts/setup/initial_config/configure_palmito_mac.sh
fixed the min gas price to be 0loya (uses the global config)
fixed mac sed commands to have the `''` after the `sed`.
=> Fix state sync scripts

daemons/custom_query/combined/combined_handler/vyusd_price_handler.go, daemons/custom_query/config.go, daemons/custom_query/constants.go, daemons/custom_query/default_custom_query_config.go, daemons/custom_query/request.go, e2e/startup_using_wrong_key_test.go, prod-sim/chain/exported_data/default_docker_genesis.json, prod-sim/chain/genesis/genesis.json
implemented telemetry metrics inside of the custom queries so that we can track all sources
Fixes #
- [ x ] New feature
- [ x ] Daemon Changes
ran on local docker set up and verified the prometheus data was collected in the browser
- [ x ] Code follows project style guidelines
- [ x ] I have added appropriate comments to my code
- [ x ] I have updated the documentation accordingly
- [ x ] I have added tests that prove my fix or feature works
- [ x ] go test ./... is passing locally
- [ x ] make e2e is passing locally
=> Add telemetry to custom sources

daemons/custom_query/contracts/contract_handlers/rocket_pool_eth.go, daemons/custom_query/contracts/contract_handlers/rocket_pool_eth_test.go
Fix bug in reth price handler to do the appropriate conversion. Tested it by reporting to testnet
Fixes #
=> Fix reth handler calculation

evm/hardhat.config.js, evm/scripts/UpgradeSepolia.js
=> sepolia upgrade script

adr/adr2012 - domain separator and testnet upgrade.md
Fixes #
- [ x ] Documentation update
- [x ] Code follows project style guidelines
- [ x] I have added appropriate comments to my code
- [ x] I have updated the documentation accordingly
- [ x] I have added tests that prove my fix or feature works
- [ x] go test ./... is passing locally
- [ x] make e2e is passing locally
=> chore: domain separator adr
